inherit_from:
  - https://raw.githubusercontent.com/trailblazer/meta/master/rubocop.yml

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Send:
  Enabled: false
