sudo: false
language: ruby
cache: bundler
matrix:
  include:
  - rvm: 2.4.1
    env: RAILS_VERSION=4.2.10
  - rvm: 2.4.1
    env: RAILS_VERSION=5.0.7
  - rvm: 2.4.1
    env: RAILS_VERSION=5.1.6
  - rvm: 2.5.1
    env: RAILS_VERSION=5.2.0

script: bundle exec rake test

